export const imageList = [
    {
      src: require("../Images/Property1.png"),
      name: "Luxury Apartment 1",
      location: "Dublin, Ireland",
      price: "€1,500/month",
      size: "75 sqm",
      description: "A modern 2-bedroom apartment located in the heart of Dublin with stunning city views.",
      discount: "20",
    },
    {
      src: require("../Images/Property2.png"),
      name: "Cozy Studio Apartment",
      location: "Galway, Ireland",
      price: "€800/month",
      size: "35 sqm",
      description: "A fully furnished studio apartment close to Galway City Centre.",
      discount: "20"
    },
    {
      src: require("../Images/Property3.png"),
      name: "Spacious Family Home",
      location: "Cork, Ireland",
      price: "€2,000/month",
      size: "120 sqm",
      description: "A 4-bedroom family home with a large garden and garage in a quiet neighborhood.",
      discount: "20"
    },
    {
      src: require("../Images/Flat1.png"),
      name: "Modern Loft",
      location: "Limerick, Ireland",
      price: "€1,200/month",
      size: "60 sqm",
      description: "A stylish loft apartment with an open-plan living area and high ceilings.",
      discount:"20",
    },
    {
      src: require("../Images/Flat2.png"),
      name: "Beachside Retreat",
      location: "Wexford, Ireland",
      price: "€1,800/month",
      size: "95 sqm",
      description: "A luxurious beachside apartment with 3 bedrooms and breathtaking sea views.",
      discount: "20",
    },
    {
      src: require("../Images/Flat3.png"),
      name: "Penthouse Suite",
      location: "Belfast, Northern Ireland",
      price: "€3,000/month",
      size: "150 sqm",
      description: "A high-end penthouse suite with premium amenities and panoramic city views.",
      discount: "20",
    },
    {
      src: require("../Images/Newyork Appartment.jpg"),
      name: "Dublin Appartment",
      location: "Dublin, Ireland",
      price: "€1,000/month",
      size: "350 sqm",
      description: "A appartment specially for college boys/girls",
      discount: "20",
    },
    {
      src: require("../Images/Appartment.jpg"),
      name: "Penthouse Suite",
      location: "Limerick, Ireland",
      price: "€800/month",
      size: "150 sqm",
      description: "A high-end penthouse suite with amenities and panoramic city views.",
      discount: "20",
    },
    
  ];
